
┌────────────────────────────────────────────────────────┐
│                                                        │
│                                                        │
│ ########      bombardment of the virus      ########   │
├────────────────────────────────────────────────────────┤ 
│     No ano de 2046, um grupo de cientista conseguem    │
│     terminar o maior feito da humanidade “um botão de  │
│     reiniciar” uma máquina do tempo. Motivo para ser   │ 
│     comemorado pois a única salvação da terra é voltar │
│     no tempo e destruir todas as bases que contém o    │
│     vírus que acabou com quase toda a população do     │
│     planeta.                                           │
├──────────────────────────┬─────────────────────────────┤
│ Legenda dos tabuleiros   │ Base:   Tamanho             │
│ X - Bomba  perdida       │ CT          1               │  
│ @ - CT                   │ IAPA        2               │
│ # - IAPA                 │ BMT         3               │
│ o - BTM                  │ BPC         4               │
│ * - BPC                  │                             │
└──────────────────────────┴─────────────────────────────┘


┌───────── ☠ ☠ ☠ ☠  Derrota ☠ ☠ ☠ ☠ ── _____ ─┐
│ Você não foi capaz de destruir as    /     \ │
│ bases inimigas a tempo.              |() ()| │
│                                      \  ^  / │
│                                       |||||  │
│        FIM DO MUNDO !!                |||||  │
└──────────────────────────────────────────────┘
   _____                         ____    
  / ____|                       / __ \                 
 | |  __  __ _ _ __ ___   ___  | |  | |_   _____ _ __  
 | | |_ |/ _` | '_ ` _ \ / _ \ | |  | \ \ / / _ \ '__| 
 | |__| | (_| | | | | | |  __/ | |__| |\ V /  __/ |    
  \_____|\__,_|_| |_| |_|\___|  \____/  \_/ \___|_|
  
  
  
┌─────── ★ ★ ★ ★ Vitória ★ ★ ★ ★ ───┐
│ Você conseguiu destruir todas as    │
│ bases inimigas                      │
│ VOCE SALVOU O MUNDO <3              │
│                                     │
└─────────────────────────────────────┘
